WIP, switch to BUNDLED arrow build
failing because despite ARROW_JEMALLOC assuredly being OFF, the .so
is ending up with missing arrow symbols referencing jemalloc

```
ImportError: dlopen(/Users/tom/perspective/perspective/rust/perspective-python/perspective/perspective.abi3.so, 0x0002): symbol not found in flat namespace '__ZN5arrow11memory_pool8internal17JemallocAllocator13ReleaseUnusedEv'
```